SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PLAYER_MOVE_DISTANCE = 10
PLAYER_FINISH_LINE_Y = SCREEN_HEIGHT / 2 - 20

CARS_COLOURS = ('red', 'yellow', 'black', 'purple', 'blue')
STARTING_MOVE_DISTANCE = 7
CAR_MOVE_INCREMENT = 5
CARS_NUMBERS = 10

FONT = ("Courier", 24, "normal")